[29기 장예지] Signup 레이아웃 구성
wecode-bootcamp-korea/29-1st-Dr-Mataeng-frontend pull request #4
Opened 2022-01-25 12:05 UTC by yeji0803

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 회원가입에 있는 input창에 값을 알맞게 넣으면 사이트에 회원가입이 되는 기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입창 레이아웃 구성
- 회원가입 창의 레이아웃 기초를 구성 하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- flex를 이용해서 아이템을 중앙으로 정렬했을 때 정렬된 것 중 하나의 아이템만 중앙 정렬이 아닌 왼쪽에서 시작하거나
오른쪽에서 시작하게 만들고 싶을때 float을 사용했었는데 그 아이템을 display: flex 값을 주고 justify-content: start를 사용하면
기본 축에서 정렬 컨테이너의 시작 가장자리로 정렬이 되는 것을 알게되었습니다.
<br />

## :: 기타 질문 및 특이 사항
- 같은 형식이 계속 반복됩니다.(input창) 이것을 컴포넌트로 만드는 작업이 필요할것 같습니다.

2022-01-26 03:35 UTC, younuk23 requested changes
고생하셨습니다 예지님 브랜치 너무 잘 나눠주셨네요!
리뷰 확인 및 반영해주세요!

2022-01-26 03:35 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +import React, { useState } from 'react';
리뷰요청전에는 사이더 코멘트는 다 해결해주세요!

2022-01-26 03:35 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +            </div>
input 부분 반복되고 있으니까 상수데이터 및 Array.map 이용해볼 수도 있겠네요!

2022-01-26 03:35 UTC, younuk23 commented on src/pages/SignUp/SignUp.scss
> +      .phoneInput {
같은 스타일을 부여할거라면 동일한 클래스네임 하나만 부여해도 좋을 것 같네요!

2022-01-26 03:35 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +              <label for="man">남자</label>
- 아래의 코드와 같이 <label> 안에 <input> 을 중첩시킬 경우 연관이 암시적이므로 for 및 id속성이 필요없어 불필요한 속성 사용을 줄일 수 있습니다. 아래 코드 예시를 확인해주세요.

```jsx
// 수정 전
<label htmlFor="connect-type">
    <input type="checkbox" name="connect" id="connect-type" />
</label>

// 수정 후
<label>
    <input type="checkbox" name="connect" />
</label>
```

2022-01-26 03:35 UTC, younuk23 commented on package.json
> +    "react-calendar": "^3.6.0",
사용하지 않는 라이브러리는 설치하지 말아주세요!

2022-01-26 03:35 UTC, younuk23 commented
컨플릭도 해결해주세요!

2022-01-26 05:27 UTC, yeji0803 commented on src/pages/SignUp/SignUp.scss
> +      .phoneInput {
넵 하나의 클래스 네임으로 묶으니 보기가 더 깔끔해지네요~

2022-01-28 02:13 UTC, younuk23 commented
예지님! 리뷰요청하시는거면 리뷰요청 라벨 부착해주세요!

2022-01-28 08:22 UTC, younuk23 reviewed
고생하셨습니다 예지님!
수정사항 코멘트 몇개 달아드렸는데 마이너한 부분이라서 다음 작업할 때 같이 반영해주세요!
이 브랜치 머지해도 될 것 같은데 추가기능구현중 라벨이 붙어있네요! 추가기능 구현중이신가요??

2022-01-28 08:22 UTC, younuk23 commented on src/pages/Login/login.js
> +  return <div>hi</div>;
이부분은 이 브랜치에서 수정할 사항 아닌것 같네요!

2022-01-28 08:22 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +    setInputs({ ...inputs, [e.target.name]: e.target.value });
e.target 구조분해할당해서 사용하면 좀 더 깔끔해지겠네요!

2022-01-28 08:22 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +            : console.log('결과: ', result)
테스트 끝난 콘솔은 지워주세요!
테스트가 아니라 만약 명시적으로 콘솔창에 의도적으로 남기고싶은거면 단순 log보다 info, warning, error등을 활용하는게 좋습니다!

2022-01-28 08:22 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +            {INPUT_LIST.map(list => {
👍

2022-01-28 11:06 UTC, yeji0803 commented on src/pages/SignUp/SignUp.js
> +            : console.log('결과: ', result)
info로 변경했습니다~

2022-01-28 11:08 UTC, yeji0803 commented on src/pages/SignUp/SignUp.js
> +    setInputs({ ...inputs, [e.target.name]: e.target.value });
밑에 부분에 구조분해 할당해서 했는데 어떤 부분을 더 변경해야될지 잘 모르겠습니다... 구조분해할당에 대해서 더 공부 후 변경해보겠습니다~!

2022-01-28 11:09 UTC, yeji0803 commented on src/pages/SignUp/SignUp.js
> +            {INPUT_LIST.map(list => {
각각의 input창에 조건을 걸어 그 조건을 만족하지 못할때 border색이 변화하는 기능을 구현하려고 했습니다. 현재까지 진행한 회원가입 부분은 merge하고 이 부분은 따로 브런치를 파서 진행하겠습니다.!

2022-02-07 07:14 UTC, younuk23 approved these changes
고생하셨습니다 코멘트 하나 남겨드린건 확인해주세요! LGTM 👍

2022-02-07 07:14 UTC, younuk23 commented on src/pages/SignUp/SignUp.js
> +    setInputs({ ...inputs, [e.target.name]: e.target.value });
```suggestion
    const { name, value } = e.target;
    setInputs({ ...inputs, [name]: value });
```
위와 같은 변경 말씀드린거였습니다 확인 해보시고 반영하시면 될 것 같아요 :)

2022-02-07 07:14 UTC, merged